unit AppService_Impl;

// ----------------------------------------------------------------------
//  This file was automatically generated by Remoting SDK from a
//  RODL file downloaded from a server or associated with this project.
// 
//  Do not modify this file manually, or your changes will be lost when
//  it is regenerated the next time you update your RODL.
// ----------------------------------------------------------------------

{$I RemObjects.inc}

interface

uses
  {$IFDEF DELPHIXE2UP}System.SysUtils{$ELSE}SysUtils{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.Classes{$ELSE}Classes{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.TypInfo{$ELSE}TypInfo{$ENDIF},
  uROEncoding,
  uROXMLIntf,
  uROClientIntf,
  uROClasses,
  uROTypes,
  uROServer,
  uROServerIntf,
  uROSessions,
  uRORemoteDataModule,
  UKLibrary_Intf;

type
  { Forward declarations }
  TAppService = class;

  TAppService = class(TRORemoteDataModule, IAppService)
  public
    function GetSessionID(const NewParam: UnicodeString): UnicodeString; virtual;
  end;

implementation

{$IFDEF DELPHIXE2UP}
  {%CLASSGROUP 'System.Classes.TPersistent'}
{$ENDIF}
{$IFNDEF FPC}
  {$R *.dfm}
{$ENDIF}
{$IFDEF FPC}
  {$R *.lfm}
{$ENDIF}

uses
  UKLibrary_Invk;

var fClassFactory_AppService: IROClassFactory;

procedure Create_AppService(out anInstance: IInterface);
begin
  anInstance := TAppService.Create(nil);
end;

function TAppService.GetSessionID(const NewParam: UnicodeString): UnicodeString;
begin
  {$Message Hint 'GetSessionID is not implemented yet!'}
end;

initialization
  fClassFactory_AppService := TROClassFactory.Create('AppService', {$IFDEF FPC}@{$ENDIF}Create_AppService, TAppService_Invoker);
  // RegisterForZeroConf(fClassFactory_AppService, '_AppService_rosdk._tcp.');
finalization
  UnRegisterClassFactory(fClassFactory_AppService);
  fClassFactory_AppService := nil;
end.
