unit LogonService_Impl;

// ----------------------------------------------------------------------
//  This file was automatically generated by Remoting SDK from a
//  RODL file downloaded from a server or associated with this project.
// 
//  Do not modify this file manually, or your changes will be lost when
//  it is regenerated the next time you update your RODL.
// ----------------------------------------------------------------------

{$I RemObjects.inc}

interface

uses
  {$IFDEF DELPHIXE2UP}System.SysUtils{$ELSE}SysUtils{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.Classes{$ELSE}Classes{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.TypInfo{$ELSE}TypInfo{$ENDIF},
  uROEncoding,
  uROXMLIntf,
  uROClientIntf,
  uROClasses,
  uROTypes,
  uROServer,
  uROServerIntf,
  uROSessions,
  uRORemoteDataModule,
  UKLibrary_Intf;

type
  { Forward declarations }
  TLogonService = class;

  TLogonService = class(TRORemoteDataModule, ILogonService)
  public
    function _ClientConn(const ClientInfo: IXmlNode; out ServerInfo: IXmlNode): Boolean; virtual;
  end;

implementation

{$IFDEF DELPHIXE2UP}
  {%CLASSGROUP 'System.Classes.TPersistent'}
{$ENDIF}
{$IFNDEF FPC}
  {$R *.dfm}
{$ENDIF}
{$IFDEF FPC}
  {$R *.lfm}
{$ENDIF}

uses
  UKLibrary_Invk,Unit_DM_Source;

var fClassFactory_LogonService: IROClassFactory;

procedure Create_LogonService(out anInstance: IInterface);
begin
  anInstance := TLogonService.Create(nil);
end;

function TLogonService._ClientConn(const ClientInfo: IXmlNode; out ServerInfo: IXmlNode): Boolean;
var
ErrorCode:Integer;
Userinfo:PUserInfo;
I:Integer;
begin
TRY
     ClientInfo.GetNodeValue('User')

      CreateSession;
      ACT_UserDict(UserLogin,Userinfo,ErrorCode);
    FINALLY
      Dispose(Userinfo);
    END;
end;

initialization
  fClassFactory_LogonService := TROClassFactory.Create('LogonService', {$IFDEF FPC}@{$ENDIF}Create_LogonService, TLogonService_Invoker);
  // RegisterForZeroConf(fClassFactory_LogonService, '_LogonService_rosdk._tcp.');
finalization
  UnRegisterClassFactory(fClassFactory_LogonService);
  fClassFactory_LogonService := nil;
end.
